project_name: "whosthere"

before:
  hooks:
    - go mod tidy
    - go generate

builds:
  - main: ./main.go
    binary: whosthere
    goos: ["linux", "darwin"]
    goarch: ["386", "amd64", "arm64"]
    ldflags:
      - -s -w -X main.versionStr={{.Version}}
      - -X main.commitStr={{ .Commit }}
      - -X main.dateStr={{ .CurrentTag }}
    env:
      - CGO_ENABLED=0

changelog:
  sort: "asc"
  filters:
    exclude: ["^docs:", "demo", "^hugo:", "Merge pull request", "Merge branch"]

homebrew_casks:
  - name: whosthere
    binaries:
      - whosthere
    homepage: "https://github.com/ramonvermeulen/whosthere"
    description: "Local network discovery tool with a modern Terminal User Interface (TUI) written in Go."
    license: "Apache-2.0"
    skip_upload: auto
    commit_author:
      name: Ramon Vermeulen
      email: ramonvermeulen98@gmail.com
    repository:
      owner: ramonvermeulen
      name: homebrew
      branch: main
